stages:
  prepare:
    cmd: py src/prepare.py
    deps:
    - src/prepare.py
    params:
    - prepare.categories
    outs:
    - data/prepared
  featurize:
    cmd: py src/featurize.py data/prepared data/features
    deps:
    - data/prepared
    - src/featurize.py
    outs:
    - data/features
  train:
    cmd: py src/train.py data/features model.pkl
    deps:
    - data/features
    - src/train.py
    params:
    - train.alpha
    outs:
    - model.pkl
  evaluate:
    cmd: py src/evaluate.py model.pkl data/features scores.json plots.json
    deps:
    - data/features
    - model.pkl
    - src/evaluate.py
    metrics:
    - scores.json:
        cache: false
    plots:
    - plots.json:
        cache: false
